title: "Qi Liu"
name: "Qi Liu"
description: "PhD Candidate, Harvard University"

url: "https://qiliu.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name   : "Qi Liu"
  avatar : "/images/qiliu_headshot.jpg"
  bio    : "PhD Candidate, Harvard University."
  location: "Cambridge, MA"
  links:
    - label: "CV"
      url: "/files/cv.pdf"
    - label: "Google Scholar"
      url: "https://scholar.google.com/..."
